/* Generated by scripts/dither.mjs from images.manifest.json — do not edit. */
export const imagesHash = '9665c1fa';

export type Tone = "paper" | "ember" | "amber" | "ink";
export type ImageVariant = `${Tone}` | `${Tone}-dense`;
export interface ImageCredit {
  title: string;
  author: string;
  year: number | null;
  licence: string;
  licence_url: string;
  page_url: string;
  source: string;
}
export interface GeneratedImage {
  alt: string;
  aspect: number;
  variants: Partial<Record<ImageVariant, Record<number, string>>>;
  credit: ImageCredit;
}

export const images = {
  "diana": {
    "alt": "A lean collared greyhound stands in full profile on a grassy plain, tongue out; tiny riders and birds on the horizon. Etching.",
    "aspect": 1.7955112219451372,
    "variants": {
      "ember": {
        "720": "images/diana-720-ember.png",
        "1440": "images/diana-1440-ember.png"
      },
      "ember-dense": {
        "720": "images/diana-720-ember-dense.png",
        "1440": "images/diana-1440-ember-dense.png"
      },
      "paper": {
        "720": "images/diana-720-paper.png",
        "1440": "images/diana-1440-paper.png"
      },
      "paper-dense": {
        "720": "images/diana-720-paper-dense.png",
        "1440": "images/diana-1440-paper-dense.png"
      }
    },
    "credit": {
      "title": "Hazewindhond Diana",
      "author": "Gerardus Emaus de Micault",
      "year": 1819,
      "licence": "CC0 1.0",
      "licence_url": "https://creativecommons.org/publicdomain/zero/1.0/",
      "page_url": "https://commons.wikimedia.org/wiki/File:Hazewindhond_Diana,_RP-P-1884-A-8205.jpg",
      "source": "Rijksmuseum"
    }
  },
  "head": {
    "alt": "Close profile of a greyhound's head, a folded ear, a watchful eye and a buckled collar. Etching.",
    "aspect": 1.7122473246135552,
    "variants": {
      "paper": {
        "720": "images/head-720-paper.png",
        "1440": "images/head-1440-paper.png"
      },
      "paper-dense": {
        "720": "images/head-720-paper-dense.png",
        "1440": "images/head-1440-paper-dense.png"
      },
      "ember": {
        "720": "images/head-720-ember.png",
        "1440": "images/head-1440-ember.png"
      },
      "ember-dense": {
        "720": "images/head-720-ember-dense.png",
        "1440": "images/head-1440-ember-dense.png"
      }
    },
    "credit": {
      "title": "Kop van een hazewindhond",
      "author": "Joseph Mendes da Costa",
      "year": 1828,
      "licence": "CC0 1.0",
      "licence_url": "https://creativecommons.org/publicdomain/zero/1.0/",
      "page_url": "https://commons.wikimedia.org/wiki/File:Kop_van_een_hazewindhond,_RP-P-OB-48.097.jpg",
      "source": "Rijksmuseum"
    }
  },
  "stag-hunt": {
    "alt": "Hounds with their noses to the ground track stags through a wood while mounted hunters close in. Engraving.",
    "aspect": 1.411764705882353,
    "variants": {
      "paper": {
        "720": "images/stag-hunt-720-paper.png",
        "1440": "images/stag-hunt-1440-paper.png"
      },
      "paper-dense": {
        "720": "images/stag-hunt-720-paper-dense.png",
        "1440": "images/stag-hunt-1440-paper-dense.png"
      }
    },
    "credit": {
      "title": "Hertenjacht met honden (Venationes Ferarum)",
      "author": "Jan Collaert II after Stradanus",
      "year": 1596,
      "licence": "CC0 1.0",
      "licence_url": "https://creativecommons.org/publicdomain/zero/1.0/",
      "page_url": "https://commons.wikimedia.org/wiki/File:Hertenjacht_met_honden_Jachttaferelen_(serietitel)_Venationes_Ferarum,_auium,_piscium_pvgnae_Bestiariorum_(serietitel),_RP-P-1982-282.jpg",
      "source": "Rijksmuseum"
    }
  },
  "sniffer": {
    "alt": "A spotted hound with its nose pressed to the roots of a tree, cropped from a Stradanus hunting plate.",
    "aspect": 1.0278372591006424,
    "variants": {
      "paper": {
        "720": "images/sniffer-720-paper.png",
        "1440": "images/sniffer-1440-paper.png"
      },
      "paper-dense": {
        "720": "images/sniffer-720-paper-dense.png",
        "1440": "images/sniffer-1440-paper-dense.png"
      }
    },
    "credit": {
      "title": "Hertenjacht met honden (detail: a hound on the scent)",
      "author": "Jan Collaert II after Stradanus",
      "year": 1596,
      "licence": "CC0 1.0",
      "licence_url": "https://creativecommons.org/publicdomain/zero/1.0/",
      "page_url": "https://commons.wikimedia.org/wiki/File:Hertenjacht_met_honden_Jachttaferelen_(serietitel)_Venationes_Ferarum,_auium,_piscium_pvgnae_Bestiariorum_(serietitel),_RP-P-1982-282.jpg",
      "source": "Rijksmuseum"
    }
  },
  "hollar": {
    "alt": "Five piebald hunting hounds on a blank ground, seated, lying and standing; one faces the viewer. Etching.",
    "aspect": 1.5450643776824033,
    "variants": {
      "paper": {
        "720": "images/hollar-720-paper.png",
        "1440": "images/hollar-1440-paper.png"
      },
      "paper-dense": {
        "720": "images/hollar-720-paper-dense.png",
        "1440": "images/hollar-1440-paper-dense.png"
      }
    },
    "credit": {
      "title": "Vijf jachthonden",
      "author": "Wenceslaus Hollar",
      "year": 1647,
      "licence": "CC0 1.0",
      "licence_url": "https://creativecommons.org/publicdomain/zero/1.0/",
      "page_url": "https://commons.wikimedia.org/wiki/File:Vijf_jachthonden_Jacht,_jachthonden_en_wild_(serietitel),_RP-P-OB-11.595.jpg",
      "source": "Rijksmuseum"
    }
  },
  "stare": {
    "alt": "A hound's head, looking straight at the viewer, cropped from Hollar's Five hunting hounds.",
    "aspect": 1.1726384364820848,
    "variants": {
      "paper": {
        "720": "images/stare-720-paper.png",
        "1440": "images/stare-1440-paper.png"
      },
      "paper-dense": {
        "720": "images/stare-720-paper-dense.png",
        "1440": "images/stare-1440-paper-dense.png"
      }
    },
    "credit": {
      "title": "Vijf jachthonden (detail: the hound that stares back)",
      "author": "Wenceslaus Hollar",
      "year": 1647,
      "licence": "CC0 1.0",
      "licence_url": "https://creativecommons.org/publicdomain/zero/1.0/",
      "page_url": "https://commons.wikimedia.org/wiki/File:Vijf_jachthonden_Jacht,_jachthonden_en_wild_(serietitel),_RP-P-OB-11.595.jpg",
      "source": "Rijksmuseum"
    }
  },
  "chase": {
    "alt": "The head and forelegs of a hound at full stretch, cropped from Oudry's Chien courant.",
    "aspect": 1.1871393239901071,
    "variants": {
      "paper": {
        "720": "images/chase-720-paper.png",
        "1440": "images/chase-1440-paper.png"
      },
      "paper-dense": {
        "720": "images/chase-720-paper-dense.png",
        "1440": "images/chase-1440-paper-dense.png"
      }
    },
    "credit": {
      "title": "Chien courant (detail: the chase)",
      "author": "Jacques-Philippe Le Bas and Jean Eric Rehn after Jean-Baptiste Oudry",
      "year": 1745,
      "licence": "CC0 1.0",
      "licence_url": "https://creativecommons.org/publicdomain/zero/1.0/",
      "page_url": "https://commons.wikimedia.org/wiki/File:Jacques-Philippe_Le_Bas_and_Jean_Eric_Rehn_after_Jean-Baptiste_Oudry,_Chien_courent_(Running_Hound),_NGA_52102.jpg",
      "source": "National Gallery of Art, Washington"
    }
  },
  "par-force": {
    "alt": "A mounted huntsman with a French horn over his shoulder rides past an oak while a pack of spotted hounds waits below. Etching and engraving.",
    "aspect": 0.8017817371937639,
    "variants": {
      "paper": {
        "720": "images/par-force-720-paper.png",
        "1440": "images/par-force-1440-paper.png"
      },
      "paper-dense": {
        "720": "images/par-force-720-paper-dense.png",
        "1440": "images/par-force-1440-paper-dense.png"
      }
    },
    "credit": {
      "title": "Huntsman with a Pack of Hounds",
      "author": "Johann Elias Ridinger",
      "year": null,
      "licence": "CC0 1.0",
      "licence_url": "https://creativecommons.org/publicdomain/zero/1.0/",
      "page_url": "https://commons.wikimedia.org/wiki/File:Johann_Elias_Ridinger,_Huntsman_with_a_Pack_of_Hounds,_NGA_55544.jpg",
      "source": "National Gallery of Art, Washington"
    }
  },
  "pair": {
    "alt": "A wind-blown huntsman in a broad hat holds two tall greyhounds on a hillock beside a leafy tree. Engraving and etching.",
    "aspect": 1.6666666666666667,
    "variants": {
      "ember": {
        "720": "images/pair-720-ember.png",
        "1440": "images/pair-1440-ember.png"
      },
      "ember-dense": {
        "720": "images/pair-720-ember-dense.png",
        "1440": "images/pair-1440-ember-dense.png"
      }
    },
    "credit": {
      "title": "Windhonden",
      "author": "Frederick Bloemaert after Abraham Bloemaert",
      "year": 1650,
      "licence": "CC0 1.0",
      "licence_url": "https://creativecommons.org/publicdomain/zero/1.0/",
      "page_url": "https://commons.wikimedia.org/wiki/File:Windhonden_Dieren_(serietitel),_RP-P-BI-1503.jpg",
      "source": "Rijksmuseum"
    }
  },
  "eustace": {
    "alt": "Two greyhounds and three hounds wait in the undergrowth at their master's feet; a detail from Dürer's Saint Eustace. Engraving.",
    "aspect": 2.2256568778979906,
    "variants": {
      "ember": {
        "720": "images/eustace-720-ember.png",
        "1440": "images/eustace-1440-ember.png"
      },
      "ember-dense": {
        "720": "images/eustace-720-ember-dense.png",
        "1440": "images/eustace-1440-ember-dense.png"
      },
      "paper": {
        "720": "images/eustace-720-paper.png",
        "1440": "images/eustace-1440-paper.png"
      },
      "paper-dense": {
        "720": "images/eustace-720-paper-dense.png",
        "1440": "images/eustace-1440-paper-dense.png"
      }
    },
    "credit": {
      "title": "Saint Eustace (detail: the hounds)",
      "author": "Albrecht Dürer",
      "year": 1501,
      "licence": "CC0 1.0",
      "licence_url": "https://creativecommons.org/publicdomain/zero/1.0/",
      "page_url": "https://commons.wikimedia.org/wiki/File:Albrecht_D%C3%BCrer,_Saint_Eustace,_c._1500-1501,_NGA_35100.jpg",
      "source": "National Gallery of Art, Washington"
    }
  },
  "fyt": {
    "alt": "A dark greyhound stoops over dead game among rocks and thistles, a hunting rifle in the foreground. Etching.",
    "aspect": 1.3793103448275863,
    "variants": {
      "paper": {
        "720": "images/fyt-720-paper.png",
        "1440": "images/fyt-1440-paper.png"
      },
      "paper-dense": {
        "720": "images/fyt-720-paper-dense.png",
        "1440": "images/fyt-1440-paper-dense.png"
      }
    },
    "credit": {
      "title": "Landscape with Greyhound and Rifle",
      "author": "Jan Fyt",
      "year": 1642,
      "licence": "CC0 1.0",
      "licence_url": "https://creativecommons.org/publicdomain/zero/1.0/",
      "page_url": "https://commons.wikimedia.org/wiki/File:Jan_Fyt,_Landscape_with_Greyhound_and_Rifle,_1642,_NGA_55434.jpg",
      "source": "National Gallery of Art, Washington"
    }
  },
  "bloodhound": {
    "alt": "Two dark bloodhounds stand in a woodland clearing, heads turned, noses working. Engraving.",
    "aspect": 1.332099907493062,
    "variants": {
      "paper": {
        "720": "images/bloodhound-720-paper.png",
        "1440": "images/bloodhound-1440-paper.png"
      },
      "paper-dense": {
        "720": "images/bloodhound-720-paper-dense.png",
        "1440": "images/bloodhound-1440-paper-dense.png"
      }
    },
    "credit": {
      "title": "Blood Hounds",
      "author": "James Westley after Samuel Howitt",
      "year": 1828,
      "licence": "Public domain",
      "licence_url": "https://commons.wikimedia.org/wiki/Template:PD-old-100-expired",
      "page_url": "https://commons.wikimedia.org/wiki/File:Bloodhounds_1826.jpg",
      "source": "Wikimedia Commons"
    }
  },
  "lying": {
    "alt": "A dark greyhound lies on the ground, head raised and ears pricked, against sketchy grass. Etching.",
    "aspect": 1.9699042407660738,
    "variants": {
      "ember": {
        "720": "images/lying-720-ember.png",
        "1440": "images/lying-1440-ember.png"
      },
      "ember-dense": {
        "720": "images/lying-720-ember-dense.png",
        "1440": "images/lying-1440-ember-dense.png"
      },
      "paper": {
        "720": "images/lying-720-paper.png",
        "1440": "images/lying-1440-paper.png"
      },
      "paper-dense": {
        "720": "images/lying-720-paper-dense.png",
        "1440": "images/lying-1440-paper-dense.png"
      }
    },
    "credit": {
      "title": "Liggende hazewindhond",
      "author": "Otto Eerelman",
      "year": null,
      "licence": "CC0 1.0",
      "licence_url": "https://creativecommons.org/publicdomain/zero/1.0/",
      "page_url": "https://commons.wikimedia.org/wiki/File:Liggende_hazewindhond,_RP-P-1912-81.jpg",
      "source": "Rijksmuseum"
    }
  },
  "dasveldt": {
    "alt": "A greyhound lies alert in the grass, head up and watching, while a second greyhound runs off towards the horizon behind it. Etching.",
    "aspect": 1.2926391382405744,
    "variants": {
      "paper": {
        "720": "images/dasveldt-720-paper.png",
        "1440": "images/dasveldt-1440-paper.png"
      },
      "paper-dense": {
        "720": "images/dasveldt-720-paper-dense.png",
        "1440": "images/dasveldt-1440-paper-dense.png"
      }
    },
    "credit": {
      "title": "Hazewindhonden",
      "author": "Jan Dasveldt",
      "year": 1800,
      "licence": "CC0 1.0",
      "licence_url": "https://creativecommons.org/publicdomain/zero/1.0/",
      "page_url": "https://commons.wikimedia.org/wiki/File:Hazewindhonden,_RP-P-1882-A-5002.jpg",
      "source": "Rijksmuseum"
    }
  },
  "tempesta": {
    "alt": "A stag hunt: a rider with a raised spear, hounds leaping at the quarry, more riders and hounds streaming across the open country behind. Etching.",
    "aspect": 1.3846153846153846,
    "variants": {
      "ember": {
        "720": "images/tempesta-720-ember.png",
        "1440": "images/tempesta-1440-ember.png"
      },
      "ember-dense": {
        "720": "images/tempesta-720-ember-dense.png",
        "1440": "images/tempesta-1440-ember-dense.png"
      }
    },
    "credit": {
      "title": "Jacht op herten",
      "author": "After Antonio Tempesta",
      "year": 1624,
      "licence": "CC0 1.0",
      "licence_url": "https://creativecommons.org/publicdomain/zero/1.0/",
      "page_url": "https://commons.wikimedia.org/wiki/File:Jacht_op_herten_Jachttaferelen_(serietitel)_Iachtboeck_(serietitel_op_object),_RP-P-OB-68.109.jpg",
      "source": "Rijksmuseum"
    }
  }
} as const satisfies Record<string, GeneratedImage>;

export type ImageId = keyof typeof images;
